ALTER TABLE servers
    DROP COLUMN IF EXISTS address,
    DROP COLUMN IF EXISTS status,
    DROP COLUMN IF EXISTS vcpus,
    DROP COLUMN IF EXISTS mem_mib,
    DROP COLUMN IF EXISTS os,
    DROP COLUMN IF EXISTS arch,
    DROP COLUMN IF EXISTS version,
    DROP COLUMN IF EXISTS projects,
    DROP COLUMN IF EXISTS vms,
    DROP COLUMN IF EXISTS last_seen;
