ALTER TABLE roles DROP COLUMN IF EXISTS is_system;
ALTER TABLE roles DROP COLUMN IF EXISTS is_default;
ALTER TABLE roles DROP COLUMN IF EXISTS sees_all;
ALTER TABLE roles DROP COLUMN IF EXISTS is_admin;
ALTER TABLE roles DROP COLUMN IF EXISTS scope;
