#!/usr/bin/env bash
# ============================================================================
#  Porter dev environment — Docker-backed PostgreSQL + local binary, real
#  microVM boots through the official Firecracker HTTP API over Unix sockets.
#  Run from anywhere inside backend/. On a host without KVM, `porter` still
#  starts the control plane and dashboard, but direct VM boots remain disabled.
#
#   bash scripts/backend/dev.sh up          # start postgres, build, run server
#   bash scripts/backend/dev.sh down        # stop the postgres container (keeps data)
#   bash scripts/backend/dev.sh rm          # stop + delete container + data volume
#   bash scripts/backend/dev.sh logs        # follow postgres logs
#   bash scripts/backend/dev.sh status      # show container + porter state
#   bash scripts/backend/dev.sh clean       # down + remove ./bin and local porter.db
#
#  The API + dashboard come up on http://localhost:8080. The initial account
#  is seeded by migration and initialized with PORTER_BOOTSTRAP_ADMIN_PASSWORD.
# ============================================================================
set -euo pipefail

DB_CONTAINER=${PORTER_DB_CONTAINER:-porter-db}
DB_PORT=${PORTER_DB_PORT:-5432}
DB_USER=${PORTER_DB_USER:-porter}
DB_PASSWORD=${PORTER_DB_PASSWORD:-porter}
DB_NAME=${PORTER_DB_NAME:-porter}
DB_IMAGE=${PORTER_DB_IMAGE:-postgres:16}
ADDR=${PORTER_LISTEN_ADDR:-:8080}

# Repository root is two levels up from this script; Go code lives in backend/.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BACKEND_DIR="$REPO_DIR/backend"
STATE_DIR=${PORTER_STATE_DIR:-$REPO_DIR/.dev/state}
FIRECRACKER_BIN=${PORTER_FIRECRACKER_BIN:-$STATE_DIR/bin/firecracker}
cd "$BACKEND_DIR"

c()  { printf '\n\033[1;34m==> %s\033[0m\n' "$1"; }
ok() { printf '\033[0;32m    ok: %s\033[0m\n' "$1"; }
die(){ printf '\033[0;31m    FAIL: %s\033[0m\n' "$1" >&2; exit 1; }

require_docker() {
  command -v docker >/dev/null 2>&1 || die "docker not found — dev.sh uses Docker for PostgreSQL. Install Docker Desktop (Windows/macOS) or the docker CLI."
  docker info >/dev/null 2>&1 || die "docker daemon not reachable — start Docker first."
}

db_url() { printf 'postgres://%s:%s@localhost:%s/%s?sslmode=disable' "$DB_USER" "$DB_PASSWORD" "$DB_PORT" "$DB_NAME"; }

db_start() {
  require_docker
  if docker ps --format '{{.Names}}' | grep -qx "$DB_CONTAINER"; then
    ok "postgres container '$DB_CONTAINER' already running"
    return
  fi
  if docker ps -a --format '{{.Names}}' | grep -qx "$DB_CONTAINER"; then
    c "Starting existing postgres container '$DB_CONTAINER'"
    docker start "$DB_CONTAINER" >/dev/null
  else
    c "Creating postgres container '$DB_CONTAINER' ($DB_IMAGE)"
    docker run -d \
      --name "$DB_CONTAINER" \
      -p "$DB_PORT:5432" \
      -e "POSTGRES_USER=$DB_USER" \
      -e "POSTGRES_PASSWORD=$DB_PASSWORD" \
      -e "POSTGRES_DB=$DB_NAME" \
      -e "PGDATA=/var/lib/postgresql/data/pgdata" \
      "$DB_IMAGE" >/dev/null
  fi
  c "Waiting for postgres to accept connections"
  for _ in $(seq 1 30); do
    if docker exec "$DB_CONTAINER" pg_isready -U "$DB_USER" -d "$DB_NAME" >/dev/null 2>&1; then
      ok "postgres ready on 127.0.0.1:$DB_PORT"
      return
    fi
    sleep 1
  done
  die "postgres did not become ready in time — check: docker logs $DB_CONTAINER"
}

build_binary() {
  command -v go >/dev/null 2>&1 || die "go not found — install Go 1.25+ (https://go.dev/dl)."
  c "Building ./bin/porter"
  mkdir -p bin
  go build -o bin/porter ./cmd/porter
  ok "built ./bin/porter"
}

write_config() {
  if [ -f porter.toml ]; then
    ok "porter.toml already present — leaving as-is (remove it to regenerate)"
    return
  fi
  c "Writing dev porter.toml (direct Firecracker over per-VM Unix sockets)"
  cat > porter.toml <<EOF
# Auto-generated by scripts/backend/dev.sh — real-mode config (no simulation).
[server]
listen_addr = "$ADDR"
base_domain = "porter.dev"

[database]
url          = "$(db_url)"
auto_migrate = true

[firecracker]
runtime_mode      = "direct"
base_image_ref    = "base://default"
api_socket_dir    = "$STATE_DIR/sockets"
kernel_image      = "$STATE_DIR/base-images/default/vmlinux"
rootfs_path       = "$STATE_DIR/base-images/default/rootfs.ext4"
firecracker_bin   = "$FIRECRACKER_BIN"
logs_dir          = "$STATE_DIR/logs"
images_dir        = "$STATE_DIR/images"
custom_images_dir = "$STATE_DIR/custom"
EOF
  ok "wrote porter.toml (direct Firecracker mode)"
}

up() {
  db_start
  build_binary
  write_config
  c "Starting Porter — dashboard on http://localhost${ADDR}"
  exec ./bin/porter server -config porter.toml
}

down() {
  require_docker
  if docker ps --format '{{.Names}}' | grep -qx "$DB_CONTAINER"; then
    docker stop "$DB_CONTAINER" >/dev/null
    ok "stopped postgres container '$DB_CONTAINER' (data kept)"
  else
    ok "postgres container '$DB_CONTAINER' not running"
  fi
}

rm_container() {
  down
  docker rm -f "$DB_CONTAINER" >/dev/null 2>&1 || true
  ok "removed postgres container '$DB_CONTAINER'"
}

logs() {
  require_docker
  docker logs -f "$DB_CONTAINER"
}

status() {
  echo "docker container: $(docker ps -a --format '{{.Names}}: {{.Status}}' | grep "^$DB_CONTAINER:" || echo 'porter-db not created')"
  if [ -x bin/porter ]; then
    echo "porter binary:     ./bin/porter $(./bin/porter version 2>/dev/null || echo built)"
  else
    echo "porter binary:     not built (run: bash scripts/backend/dev.sh up)"
  fi
  if [ -f porter.toml ]; then
    echo "config:            porter.toml (real mode)"
  else
    echo "config:            none (run: bash scripts/backend/dev.sh up)"
  fi
}

clean() {
  down
  rm -rf bin porter.db 2>/dev/null || true
  ok "removed ./bin and ./porter.db"
}

case "${1:-up}" in
  up)     up ;;
  down)   down ;;
  rm)     rm_container ;;
  logs)   logs ;;
  status) status ;;
  clean)  clean ;;
  *) echo "usage: bash scripts/backend/dev.sh {up|down|rm|logs|status|clean}" >&2; exit 1 ;;
esac
