package buildkit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// InitPath is where the shim is installed; Firecracker's default boot args
// run /sbin/init as PID 1.
const InitPath = "sbin/init"

// shQuote single-quotes s for POSIX sh.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// validEnvName reports whether k is a legal shell variable name.
func validEnvName(k string) bool {
	if k == "" {
		return false
	}
	for i, r := range k {
		switch {
		case r == '_', r >= 'A' && r <= 'Z', r >= 'a' && r <= 'z':
		case r >= '0' && r <= '9' && i > 0:
		default:
			return false
		}
	}
	return true
}

// BuildInitScript renders a POSIX sh PID-1 shim from an OCI image config.
// It mounts the pseudo filesystems, exports ENV, cd's to WORKDIR and execs
// ENTRYPOINT+CMD, so the converted image runs its real workload instead of
// kernel-panicking on a missing /sbin/init.
func BuildInitScript(entrypoint, cmd, env []string, workdir string) (string, error) {
	argv := append(append([]string{}, entrypoint...), cmd...)
	if len(argv) == 0 {
		return "", fmt.Errorf("image has no ENTRYPOINT or CMD; nothing to run as PID 1")
	}
	var b strings.Builder
	b.WriteString("#!/bin/sh\n# generated by porter: OCI config -> PID 1\n")
	b.WriteString("mount -t proc proc /proc 2>/dev/null\n")
	b.WriteString("mount -t sysfs sys /sys 2>/dev/null\n")
	b.WriteString("mount -t devtmpfs dev /dev 2>/dev/null\n")
	b.WriteString("mkdir -p /dev/pts /dev/shm && mount -t devpts devpts /dev/pts 2>/dev/null\n")
	b.WriteString("mount -t tmpfs tmpfs /tmp 2>/dev/null\n")
	b.WriteString("export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n")
	for _, kv := range env {
		k, v, ok := strings.Cut(kv, "=")
		if !ok || !validEnvName(k) {
			continue
		}
		fmt.Fprintf(&b, "export %s=%s\n", k, shQuote(v))
	}
	if workdir != "" {
		fmt.Fprintf(&b, "cd %s || exit 1\n", shQuote(workdir))
	}
	b.WriteString("exec")
	for _, a := range argv {
		b.WriteString(" " + shQuote(a))
	}
	b.WriteString("\n")
	return b.String(), nil
}

// InstallInit writes the shim to <root>/sbin/init (mode 0755), replacing any
// existing file or symlink (Alpine/Debian ship /sbin/init as a symlink to
// busybox/systemd, which we must not write *through*).
func InstallInit(root, script string) error {
	dst := filepath.Join(root, InitPath)
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	if err := os.Remove(dst); err != nil && !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(dst, []byte(script), 0o755)
}
